// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const FUNCTIONS_URL = import.meta.env.VITE_FUNCTIONS_URL;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const clientOptions: any = {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
};

if (FUNCTIONS_URL) {
  clientOptions.functions = {
    url: FUNCTIONS_URL,
  };
}

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  clientOptions
);